### ISSUE TITLE
Pi W Zero Make Issue

### ISSUE THREAD

**Issue by drewablo** [seemoo-lab/nexmon#83]
When I run "Make" after cd into /nexmon/patches/bcm43438/7_45_41_26/nexmon, I get the following errors. I'm running Jessie Lite 4.9.24+. 

`  BUILDING DRIVER  brcmfmac/brcmfmac.ko (details: log/driver.log)
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:136:12: error: 'IEEE80211_BAND_2GHZ' undeclared here (not in a function)
  .band   = IEEE80211_BAND_2GHZ,  \
            ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:154:2: note: in expansion of macro 'CHAN2G'
  CHAN2G(1, 2412), CHAN2G(2, 2417), CHAN2G(3, 2422), CHAN2G(4, 2427),
  ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:145:12: error: 'IEEE80211_BAND_5GHZ' undeclared here (not in a function)
  .band   = IEEE80211_BAND_5GHZ,  \
            ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:161:2: note: in expansion of macro 'CHAN5G'
  CHAN5G(34), CHAN5G(36), CHAN5G(38), CHAN5G(40), CHAN5G(42),
  ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:161:2: error: initializer element is not constant
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:161:2: error: (near initialization for '__wl_5ghz_channels[0].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:161:2: error: initializer element is not constant
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:161:2: error: (near initialization for '__wl_5ghz_channels[1].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:161:2: error: initializer element is not constant
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:161:2: error: (near initialization for '__wl_5ghz_channels[2].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:161:2: error: initializer element is not constant
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:161:2: error: (near initialization for '__wl_5ghz_channels[3].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:161:2: error: initializer element is not constant
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:161:2: error: (near initialization for '__wl_5ghz_channels[4].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:162:2: error: initializer element is not constant
  CHAN5G(44), CHAN5G(46), CHAN5G(48), CHAN5G(52), CHAN5G(56),
  ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:162:2: error: (near initialization for '__wl_5ghz_channels[5].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:162:2: error: initializer element is not constant
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:162:2: error: (near initialization for '__wl_5ghz_channels[6].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:162:2: error: initializer element is not constant
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:162:2: error: (near initialization for '__wl_5ghz_channels[7].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:162:2: error: initializer element is not constant
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:162:2: error: (near initialization for '__wl_5ghz_channels[8].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:162:2: error: initializer element is not constant
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:162:2: error: (near initialization for '__wl_5ghz_channels[9].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:163:2: error: initializer element is not constant
  CHAN5G(60), CHAN5G(64), CHAN5G(100), CHAN5G(104), CHAN5G(108),
  ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:163:2: error: (near initialization for '__wl_5ghz_channels[10].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:163:2: error: initializer element is not constant
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:163:2: error: (near initialization for '__wl_5ghz_channels[11].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:163:2: error: initializer element is not constant
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:163:2: error: (near initialization for '__wl_5ghz_channels[12].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:163:2: error: initializer element is not constant
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:163:2: error: (near initialization for '__wl_5ghz_channels[13].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:163:2: error: initializer element is not constant
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:163:2: error: (near initialization for '__wl_5ghz_channels[14].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:164:2: error: initializer element is not constant
  CHAN5G(112), CHAN5G(116), CHAN5G(120), CHAN5G(124), CHAN5G(128),
  ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:164:2: error: (near initialization for '__wl_5ghz_channels[15].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:164:2: error: initializer element is not constant
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:164:2: error: (near initialization for '__wl_5ghz_channels[16].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:164:2: error: initializer element is not constant
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:164:2: error: (near initialization for '__wl_5ghz_channels[17].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:164:2: error: initializer element is not constant
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:164:2: error: (near initialization for '__wl_5ghz_channels[18].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:164:2: error: initializer element is not constant
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:164:2: error: (near initialization for '__wl_5ghz_channels[19].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:165:2: error: initializer element is not constant
  CHAN5G(132), CHAN5G(136), CHAN5G(140), CHAN5G(144), CHAN5G(149),
  ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:165:2: error: (near initialization for '__wl_5ghz_channels[20].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:165:2: error: initializer element is not constant
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:165:2: error: (near initialization for '__wl_5ghz_channels[21].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:165:2: error: initializer element is not constant
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:165:2: error: (near initialization for '__wl_5ghz_channels[22].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:165:2: error: initializer element is not constant
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:165:2: error: (near initialization for '__wl_5ghz_channels[23].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:165:2: error: initializer element is not constant
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:165:2: error: (near initialization for '__wl_5ghz_channels[24].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:166:2: error: initializer element is not constant
  CHAN5G(153), CHAN5G(157), CHAN5G(161), CHAN5G(165)
  ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:166:2: error: (near initialization for '__wl_5ghz_channels[25].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:166:2: error: initializer element is not constant
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:166:2: error: (near initialization for '__wl_5ghz_channels[26].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:166:2: error: initializer element is not constant
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:166:2: error: (near initialization for '__wl_5ghz_channels[27].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:166:2: error: initializer element is not constant
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:166:2: error: (near initialization for '__wl_5ghz_channels[28].band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:173:2: error: initializer element is not constant
  .band = IEEE80211_BAND_2GHZ,
  ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:173:2: error: (near initialization for '__wl_band_2ghz.band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:179:2: error: initializer element is not constant
  .band = IEEE80211_BAND_5GHZ,
  ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:179:2: error: (near initialization for '__wl_band_5ghz.band')
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c: In function 'chandef_to_chanspec':
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:291:7: error: 'IEEE80211_BAND_60GHZ' undeclared (first use in this function)
  case IEEE80211_BAND_60GHZ:
       ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:291:7: note: each undeclared identifier is reported only once for each function it appears in
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c: In function 'brcmf_notify_escan_complete':
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:746:3: error: incompatible type for argument 2 of 'cfg80211_scan_done'
   cfg80211_scan_done(scan_request, aborted);
   ^
In file included from /root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:23:0:
./include/net/cfg80211.h:4304:6: note: expected 'struct cfg80211_scan_info *' but argument is of type 'bool'
 void cfg80211_scan_done(struct cfg80211_scan_request *request,
      ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:746:3: warning: statement with no effect [-Wunused-value]
   cfg80211_scan_done(scan_request, aborted);
   ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/p2p.c: In function 'brcmf_p2p_notify_action_frame_rx':
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/p2p.c:1434:12: error: 'IEEE80211_BAND_2GHZ' undeclared (first use in this function)
            IEEE80211_BAND_2GHZ :
            ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/p2p.c:1434:12: note: each undeclared identifier is reported only once for each function it appears in
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/p2p.c:1435:12: error: 'IEEE80211_BAND_5GHZ' undeclared (first use in this function)
            IEEE80211_BAND_5GHZ);
            ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/p2p.c: In function 'brcmf_p2p_notify_rx_mgmt_p2p_probereq':
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/p2p.c:1899:12: error: 'IEEE80211_BAND_2GHZ' undeclared (first use in this function)
            IEEE80211_BAND_2GHZ :
            ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/p2p.c:1900:12: error: 'IEEE80211_BAND_5GHZ' undeclared (first use in this function)
            IEEE80211_BAND_5GHZ);
            ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c: In function 'brcmf_inform_single_bss':
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:2661:22: error: array subscript is not an integer
   band = wiphy->bands[IEEE80211_BAND_2GHZ];
                      ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:2661:8: warning: assignment from incompatible pointer type
   band = wiphy->bands[IEEE80211_BAND_2GHZ];
        ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:2663:22: error: array subscript is not an integer
   band = wiphy->bands[IEEE80211_BAND_5GHZ];
                      ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:2663:8: warning: assignment from incompatible pointer type
   band = wiphy->bands[IEEE80211_BAND_5GHZ];
        ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c: In function 'brcmf_inform_ibss':
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:2770:22: error: array subscript is not an integer
   band = wiphy->bands[IEEE80211_BAND_2GHZ];
                      ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:2770:8: warning: assignment from incompatible pointer type
   band = wiphy->bands[IEEE80211_BAND_2GHZ];
        ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:2772:22: error: array subscript is not an integer
   band = wiphy->bands[IEEE80211_BAND_5GHZ];
                      ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:2772:8: warning: assignment from incompatible pointer type
   band = wiphy->bands[IEEE80211_BAND_5GHZ];
        ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c: In function 'brcmf_bss_roaming_done':
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:4938:22: error: array subscript is not an integer
   band = wiphy->bands[IEEE80211_BAND_2GHZ];
                      ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:4938:8: warning: assignment from incompatible pointer type
   band = wiphy->bands[IEEE80211_BAND_2GHZ];
        ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:4940:22: error: array subscript is not an integer
   band = wiphy->bands[IEEE80211_BAND_5GHZ];
                      ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:4940:8: warning: assignment from incompatible pointer type
   band = wiphy->bands[IEEE80211_BAND_5GHZ];
        ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c: In function 'brcmf_construct_chaninfo':
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5434:21: error: array subscript is not an integer
  band = wiphy->bands[IEEE80211_BAND_2GHZ];
                     ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5434:7: warning: assignment from incompatible pointer type
  band = wiphy->bands[IEEE80211_BAND_2GHZ];
       ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5438:21: error: array subscript is not an integer
  band = wiphy->bands[IEEE80211_BAND_5GHZ];
                     ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5438:7: warning: assignment from incompatible pointer type
  band = wiphy->bands[IEEE80211_BAND_5GHZ];
       ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5449:23: error: array subscript is not an integer
    band = wiphy->bands[IEEE80211_BAND_2GHZ];
                       ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5449:9: warning: assignment from incompatible pointer type
    band = wiphy->bands[IEEE80211_BAND_2GHZ];
         ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5451:23: error: array subscript is not an integer
    band = wiphy->bands[IEEE80211_BAND_5GHZ];
                       ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5451:9: warning: assignment from incompatible pointer type
    band = wiphy->bands[IEEE80211_BAND_5GHZ];
         ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c: In function 'brcmf_enable_bw40_2g':
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5566:34: error: array subscript is not an integer
   band = cfg_to_wiphy(cfg)->bands[IEEE80211_BAND_2GHZ];
                                  ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5566:8: warning: assignment from incompatible pointer type
   band = cfg_to_wiphy(cfg)->bands[IEEE80211_BAND_2GHZ];
        ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c: In function 'brcmf_get_bwcap':
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5598:9: error: array subscript is not an integer
   bw_cap[IEEE80211_BAND_2GHZ] = band;
         ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5598:3: warning: statement with no effect [-Wunused-value]
   bw_cap[IEEE80211_BAND_2GHZ] = band;
   ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5602:10: error: array subscript is not an integer
    bw_cap[IEEE80211_BAND_5GHZ] = band;
          ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5602:4: warning: statement with no effect [-Wunused-value]
    bw_cap[IEEE80211_BAND_5GHZ] = band;
    ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5617:9: error: array subscript is not an integer
   bw_cap[IEEE80211_BAND_2GHZ] |= WLC_BW_40MHZ_BIT;
         ^
make[2]: *** [/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/p2p.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5617:3: warning: statement with no effect [-Wunused-value]
   bw_cap[IEEE80211_BAND_2GHZ] |= WLC_BW_40MHZ_BIT;
   ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5620:9: error: array subscript is not an integer
   bw_cap[IEEE80211_BAND_5GHZ] |= WLC_BW_40MHZ_BIT;
         ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5620:3: warning: statement with no effect [-Wunused-value]
   bw_cap[IEEE80211_BAND_5GHZ] |= WLC_BW_40MHZ_BIT;
   ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5623:9: error: array subscript is not an integer
   bw_cap[IEEE80211_BAND_2GHZ] |= WLC_BW_20MHZ_BIT;
         ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5623:3: warning: statement with no effect [-Wunused-value]
   bw_cap[IEEE80211_BAND_2GHZ] |= WLC_BW_20MHZ_BIT;
   ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5624:9: error: array subscript is not an integer
   bw_cap[IEEE80211_BAND_5GHZ] |= WLC_BW_20MHZ_BIT;
         ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5624:3: warning: statement with no effect [-Wunused-value]
   bw_cap[IEEE80211_BAND_5GHZ] |= WLC_BW_20MHZ_BIT;
   ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c: In function 'brcmf_update_vht_cap':
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5664:17: warning: comparison between pointer and integer
  if (band->band == IEEE80211_BAND_2GHZ)
                 ^
In file included from ./include/linux/kernel.h:13:0,
                 from /root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:19:
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c: In function 'brcmf_setup_wiphybands':
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5701:27: error: array subscript is not an integer
     nmode, vhtmode, bw_cap[IEEE80211_BAND_2GHZ],
                           ^
./include/linux/printk.h:121:18: note: in definition of macro 'no_printk'
    printk(fmt, ##__VA_ARGS__); \
                  ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5700:2: note: in expansion of macro 'brcmf_dbg'
  brcmf_dbg(INFO, "nmode=%d, vhtmode=%d, bw_cap=(%d, %d)\n",
  ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5702:11: error: array subscript is not an integer
     bw_cap[IEEE80211_BAND_5GHZ]);
           ^
./include/linux/printk.h:121:18: note: in definition of macro 'no_printk'
    printk(fmt, ##__VA_ARGS__); \
                  ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5700:2: note: in expansion of macro 'brcmf_dbg'
  brcmf_dbg(INFO, "nmode=%d, vhtmode=%d, bw_cap=(%d, %d)\n",
  ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5700:2: warning: format '%d' expects argument of type 'int', but argument 4 has type 'struct ieee80211_channel *' [-Wformat=]
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:5700:2: warning: format '%d' expects argument of type 'int', but argument 5 has type 'struct ieee80211_channel *' [-Wformat=]
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c: In function 'brcmf_setup_wiphy':
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:6002:16: error: array subscript is not an integer
    wiphy->bands[IEEE80211_BAND_2GHZ] = band;
                ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:6002:4: warning: statement with no effect [-Wunused-value]
    wiphy->bands[IEEE80211_BAND_2GHZ] = band;
    ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:6019:16: error: array subscript is not an integer
    wiphy->bands[IEEE80211_BAND_5GHZ] = band;
                ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:6019:4: warning: statement with no effect [-Wunused-value]
    wiphy->bands[IEEE80211_BAND_5GHZ] = band;
    ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c: In function 'brcmf_free_wiphy':
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:6232:18: error: array subscript is not an integer
  if (wiphy->bands[IEEE80211_BAND_2GHZ]) {
                  ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:6233:21: error: array subscript is not an integer
   kfree(wiphy->bands[IEEE80211_BAND_2GHZ]->channels);
                     ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:6233:42: error: 'struct ieee80211_channel' has no member named 'channels'
   kfree(wiphy->bands[IEEE80211_BAND_2GHZ]->channels);
                                          ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:6234:21: error: array subscript is not an integer
   kfree(wiphy->bands[IEEE80211_BAND_2GHZ]);
                     ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:6236:18: error: array subscript is not an integer
  if (wiphy->bands[IEEE80211_BAND_5GHZ]) {
                  ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:6237:21: error: array subscript is not an integer
   kfree(wiphy->bands[IEEE80211_BAND_5GHZ]->channels);
                     ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:6237:42: error: 'struct ieee80211_channel' has no member named 'channels'
   kfree(wiphy->bands[IEEE80211_BAND_5GHZ]->channels);
                                          ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:6238:21: error: array subscript is not an integer
   kfree(wiphy->bands[IEEE80211_BAND_5GHZ]);
                     ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c: In function 'brcmf_cfg80211_attach':
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:6315:18: error: array subscript is not an integer
  if (wiphy->bands[IEEE80211_BAND_2GHZ]) {
                  ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:6316:22: error: array subscript is not an integer
   cap = &wiphy->bands[IEEE80211_BAND_2GHZ]->ht_cap.cap;
                      ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:6316:43: error: 'struct ieee80211_channel' has no member named 'ht_cap'
   cap = &wiphy->bands[IEEE80211_BAND_2GHZ]->ht_cap.cap;
                                           ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:6316:51: error: request for member 'cap' in something not a structure or union
   cap = &wiphy->bands[IEEE80211_BAND_2GHZ]->ht_cap.cap;
                                                   ^
/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.c:6316:7: warning: assignment from incompatible pointer type
   cap = &wiphy->bands[IEEE80211_BAND_2GHZ]->ht_cap.cap;
       ^
make[2]: *** [/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac/cfg80211.o] Error 1
make[1]: *** [_module_/root/nexmon/patches/bcm43438/7_45_41_26/nexmon/brcmfmac] Error 2
Makefile:41: recipe for target 'brcmfmac.ko' failed
make: *** [brcmfmac.ko] Error 2
`

**Comment by wortel538** [comment]
I'm having that too, even with using the version from february..

**Comment by fossejc** [comment]
I have the same issue

**Comment by fossejc** [comment]
I was able to compile on a RPI Zero W with kernel 4.9.24+
I used the [branch brcmfmac_kernel410](https://github.com/seemoo-lab/nexmon/tree/brcmfmac_kernel410) according to the instruction of issue #85 then I had to change `4.4.9-v7l+` by `4.9.24+` in file `patches/bcm43438/7_45_41_26/nexmon/Makefile`. Finally, I followed the steps described in #55 . The only difference is in file `utilities/libnexio/Makefile` line 5 instead of `ifeq ($(shell uname -m), $(filter $(shell uname -m), armv7l armv6l))` I had to put `ifneq ($(shell uname -m), $(filter $(shell uname -m), armv7l armv6l))` or it will try to compile for an android target.
